[package]
name = "ro-soku"
version = "0.1.0"
authors = ["mirumi <mail@mirumi.tech>"]
edition = "2021"
description = "Retrieve OHLCV ro-soku (means a candle in Japanese) from any exchangeğŸ•¯ï¸"
readme = "README.md"
repository = "https://github.com/mirumirumi/ro-soku"
license = "MIT"
keywords = ["crypto", "cryptocurrency", "exchange", "trading-bot"]

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
chrono-tz = "0.8.1"
clap = { version = "4.2.2", features = ["derive"] }
rand = "0.8.5"
regex = "1.7.3"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.40"
